export const content = [
  {
    id: 0,
    title: "Lorem ipsum dolor",
    description: "Sit amet consectetur adipisicing elit",
    text: "Maxime hic odit sunt et dicta iusto aliquam totam iure exercitationem dolorem, vel laboriosam pariatur at perspiciatis quam! Nostrum dignissimos magni natus amet odio voluptatibus, numquam eius nisi placeat ipsum dicta sit est aspernatur qui hic, praesentium reiciendis laborum expedita voluptatem aliquid dolor atque vitae? Amet, quae saepe molestiae alias blanditiis porro officiis ut tenetur quo quibusdam dolor quod voluptate harum quaerat esse. Eligendi error maiores officia voluptas dolor iure deserunt soluta, harum illo minima dignissimos atque, veritatis ipsum optio quo autem, iusto cumque illum architecto nemo nulla quod. Officia dignissimos consequatur enim asperiores veniam blanditiis nesciunt consequuntur reiciendis ipsum optio unde odio, facilis sit, sint minus deleniti ducimus reprehenderit! Nisi corrupti reiciendis dolorem, doloremque culpa fugit repellat quas voluptas aspernatur atque suscipit eos fuga, ipsam ullam sunt laboriosam? Accusamus aut porro nam, fugit incidunt nulla corporis earum molestias expedita minus? Itaque, accusamus velit maxime placeat impedit quo fugiat aut, sit voluptatum in, debitis dolore? Quis provident quos est ducimus quidem eveniet facere accusamus quia, asperiores optio odit sapiente qui a. Officiis ducimus alias minus eveniet nesciunt omnis quos. Eos similique beatae doloremque quaerat blanditiis voluptates laborum corporis perferendis voluptatibus. Culpa, asperiores.",
    imgSrc:
      "https://images.unsplash.com/photo-1607877361964-bf792b65e593?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: 1,
    title: "Hic eligendi qui ducimus",
    description: "Aspernatur est corrupti, nihil nulla adipis",
    text: "Hic eligendi qui ducimus aspernatur est corrupti, nihil nulla deserunt tenetur ratione eos amet culpa repellat sunt? Alias velit minus consequuntur, nihil tenetur sint libero iste nesciunt earum quisquam! Veniam pariatur tenetur molestiae eos beatae odit! Nostrum beatae autem corrupti et fugit aliquid quo consequuntur delectus reprehenderit repudiandae, alias explicabo atque dolore quia praesentium perferendis quasi! Autem, assumenda doloremque. Illum eligendi dolorem veniam tempore, ipsum ab sint dolorum perspiciatis illo optio debitis, repellat accusamus reprehenderit nam maxime soluta mollitia saepe nisi rerum. Nihil voluptas iusto animi itaque debitis mollitia eos! Repudiandae cum exercitationem similique eveniet libero quo magnam blanditiis. Quas deleniti ipsa officiis aliquid. Ut non rem omnis facilis beatae amet! Possimus nesciunt deserunt libero sit incidunt ad ratione distinctio molestiae, deleniti inventore nihil obcaecati quidem odio iusto aut saepe quasi sapiente mollitia unde quia a veritatis quo nam. Ut facilis minus sint nam maiores quo mollitia eligendi ducimus consequuntur dolore illo consectetur delectus temporibus ratione asperiores id quod, suscipit voluptatum nihil quisquam amet unde repellendus. Nesciunt cupiditate distinctio ducimus. Ut qui quas laudantium magnam dolore voluptate voluptatem tempora. Suscipit necessitatibus deleniti veritatis numquam quidem aliquid, voluptate nostrum debitis tempore, porro maxime.",
    imgSrc:
      "https://images.unsplash.com/photo-1602526430780-782d6b1783fa?ixlib=rb-1.2.1&ixid=MXwxMjA3fDF8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: 2,
    title: "Totam quae, distinctio",
    description: "Consequatur architecto deleniti delectus",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Numquam facilis quas temporibus quae iure hic labore alias, adipisci molestias aspernatur ratione iste non quod cumque obcaecati excepturi! Modi voluptatem veniam id soluta atque! Voluptatem, tempora totam laboriosam facilis amet autem quisquam numquam molestias, adipisci neque eligendi officiis? Tenetur eius placeat at et voluptas alias, maxime cum molestiae incidunt hic nemo blanditiis voluptatum, tempora animi ipsam illo autem dolorem minima vel ipsum? Consequatur architecto deleniti delectus quam doloremque esse vel! Vitae odit, ipsa explicabo suscipit, ullam, tempore ipsum voluptates inventore numquam assumenda magnam. Dolorum, aut veniam, possimus doloribus error distinctio nesciunt laboriosam illum neque eius, totam quod a facilis repudiandae labore sit voluptate quaerat ab consequuntur ad consequatur iste nostrum. Repellat, sunt? Aliquid similique quaerat possimus dolorem, suscipit deserunt illo ea. Architecto eveniet, id corporis ut quisquam magnam delectus officia consectetur unde, vero temporibus ipsa expedita similique natus dolorum quaerat modi? Totam quae, distinctio minima harum hic veritatis quibusdam natus a qui, eaque pariatur sapiente facilis minus ex aut aliquam, vitae exercitationem doloremque assumenda illum. Nulla placeat soluta enim voluptates eveniet quod saepe laudantium deserunt ratione ab beatae reprehenderit nostrum, voluptatum, repudiandae et pariatur, consequatur corrupti nam hic consequuntur rerum rem.",
    imgSrc:
      "https://images.unsplash.com/photo-1607883858341-ffffcef94d44?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: 3,
    title: "Voluptas quisquam",
    description: "Quia, pariatur sapiente!",
    text: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eligendi magnam ad nam, maiores placeat nulla, quia optio excepturi eos animi aut suscipit ipsum veniam, deserunt quod? Totam ex qui voluptates ullam maiores consectetur temporibus tempore quia deleniti eligendi eos eveniet ab doloremque, dolorum minima unde ad rerum expedita consequuntur fugit quidem perferendis? Aut illum saepe dolorem magni cupiditate quibusdam aperiam. Nulla quo similique velit culpa dolor. Iusto, saepe non. At, asperiores necessitatibus nesciunt magni numquam nisi officiis quasi ratione illum? Ullam eligendi, sapiente nisi obcaecati officia facere voluptatum commodi. Ex ea quas cumque tempore tenetur aliquam earum temporibus sequi odio, veniam sapiente harum asperiores molestias nemo soluta cum in veritatis voluptatibus accusantium beatae necessitatibus fugit! Voluptas quisquam, ipsam aperiam dignissimos deserunt quibusdam error aspernatur odio dolore modi, tempora, laborum quos labore provident quae ab mollitia adipisci. Impedit veniam voluptas fuga minima fugit alias commodi voluptatem esse neque fugiat beatae suscipit a tempore nisi perferendis perspiciatis cupiditate excepturi, quaerat cumque saepe aspernatur molestiae. Consectetur maiores, vel tenetur ducimus dolor id facilis minima eum. Dignissimos omnis accusamus eum voluptas asperiores non reprehenderit? Quia, pariatur sapiente! Unde aspernatur ab impedit totam autem nemo, hic minima eligendi, quo, quam assumenda quas alias accusantium ex?",
    imgSrc:
      "https://images.unsplash.com/photo-1499951360447-b19be8fe80f5?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1200&q=80s",
  },
];
